model:
  context_length: 256
  vocab_size: 50257
  num_layers: 6
  d_model: 512
  d_feedforward: 2048
  num_heads: 8
train:
  run_name: context_256
  epochs: 1
  batch_size: 32
  lr: 0.0001
  seed: 1738
  validate_freq: 500